version: '3.8'

services:
  backend:
    container_name: ${SERVICE_NAME}-backend
    image: blueconecell/syukainvest-backend:latest
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
      - mongodb
      - redis

    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MYSQL_CONTAINER_NAME=${MYSQL_CONTAINER_NAME}
      - MYSQL_HOST_PORT=${MYSQL_HOST_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MONGO_CONTAINER_NAME=${MONGO_CONTAINER_NAME}
      - MONGO_HOST_PORT=${MONGO_HOST_PORT}
      - MONGO_DB_NAME=${MONGO_DB_NAME}
      - MONGO_DB_USER=${MONGO_DB_USER}
      - MONGO_DB_PASSWORD=${MONGO_DB_PASSWORD}
      - REDIS_CONTAINER_NAME=${REDIS_CONTAINER_NAME}
      - REDIS_HOST_PORT=${REDIS_HOST_PORT}
      - BACKEND_URL=${BACKEND_URL}
